### ISSUE TITLE
Links are broken on https://oslc.github.io/developing-oslc-applications/

### ISSUE THREAD

**Issue by jadelkhoury** [OSLC/developing-oslc-applications#11]
When I test on my localhost, I have links such as
http://localhost:9000/tutorials.html
http://localhost:9000/why-develop-oslc-applications.html

Once deployed, the links become:
https://oslc.github.io/developing-oslc-applications/tutorials.html
https://oslc.github.io/developing-oslc-applications/why-develop-oslc-applications.html

But that means that relative links between documents are broken.

For example, 

* starting from https://oslc.github.io/developing-oslc-applications/tutorials.html, the link on " walkthrough tutorial" works on my local machine, but is broken on the site.
* Links from https://oslc.github.io/developing-oslc-applications/integrating_products_with_oslc/ are also broken.

The problem is because I am using urls starting with "/", such as "/tutorials."
How can I make it work both on my local machine, and the site?

**Comment by jadelkhoury** [comment]
@berezovskyi Any insights into this?

I can see only 1 solutions:

user relative urls (such as "./tutorials"). But that makes the pages less mobile. 

I thought i can also start all urls with "/developing-oslc-applications", but then the pages wont work on localhost for my own testing

**Comment by berezovskyi** [comment]
> The problem is because I am using urls starting with "/", such as "/tutorials."
How can I make it work both on my local machine, and the site?

Well, how about you don't?

> user relative urls (such as "./tutorials"). 

please do

> that makes the pages less mobile

well, anytime you move markdown files around, you got to update the links...

actually, the more you rely on relative links, the less you need to worry about where the site is deployed etc.

**Comment by jadelkhoury** [comment]
ok. I googled and that seems to be the case.
@jamsden seems to have also used relative urls ("./xxx") in the iotp_adaptor documentation, which also involves many pages. 
and I thought i was done with docuentation for the week :-(

**Comment by berezovskyi** [comment]
There is no need strictly to put "./" in front, just drop the slash.

**Comment by berezovskyi** [comment]
If I may suggest...

![image](https://user-images.githubusercontent.com/64734/58279811-a13e5680-7d9f-11e9-95ef-768e294c1e66.png)

**Comment by jadelkhoury** [comment]
Oh thank you.

**Comment by jadelkhoury** [comment]
Just so you know, ending a url with an innocent "/" will also lead to a broken link! the generator does not seem to produce ".html" in that case.

**Comment by berezovskyi** [comment]
Interesting

--
/Andrew
(from phone)



On Thu, May 23, 2019 at 9:59 PM +0200, "Jad El-khoury" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just so you know, ending a url with an innocent "/" will also lead to a broken link! the generator does not seem to produce ".html" in that case.

**Comment by jadelkhoury** [comment]
Solved.
