### ISSUE TITLE
The Landfill Links are Broken

### ISSUE THREAD

**Issue by shameerkc** [OSLC/developing-oslc-applications#12]
The Bugzilla Landfill links provided are no longer running live ([https://landfill.bugzilla.org/bugzilla-4.2-branch/createaccount.cgi](https://landfill.bugzilla.org/bugzilla-4.2-branch/createaccount.cgi))

Just wanted to know if this is still maintained actively...

**Comment by jadelkhoury** [comment]
I have recently migrated this content to https://oslc.github.io/developing-oslc-applications/tutorials.html in the hope that we can keep it more up to date.

But indeed, the current instructions do not reflect the latest changes that occured at Bugzilla. The idea I believe is that one installs Bugzilla (or maybe even getting a docker container https://hub.docker.com/search?q=bugzilla&type=image ?) instead.

If you have any chance to suggest updates you are more than welcome.

**Comment by shameerkc** [comment]
Thank you @jadelkhoury for the additional details.

I am new to OSLC and was trying to setup the examples on my own. I rather created a new repository [https://github.com/shameerkc/OSLC-Lyo-Workshop-Projects](https://github.com/shameerkc/OSLC-Lyo-Workshop-Projects) instead of forking the changes and adding up.

I am using IntelliJ IDEA and saw that the original project had multiple project setting files being checked in the repo.

Of course we need to work further to see how to update the current examples and documentation on the main project page.

Please have a look at [my example settinsg](https://github.com/shameerkc/OSLC-Lyo-Workshop-Projects) and suggest how we should move forward.

**Comment by jadelkhoury** [comment]
Hi!
I'm happy to help, and I'd see this as an opportunity to update this documentation. 
Where exactly are you stuck (if at all)? I am hoping the only missing thing is to setup your own Bugzilla instead of using Landfill.

**Comment by shameerkc** [comment]
Hi,

Below were the issues I faced while trying to setup:

- [ ] POM - The java version needs to be provided correctly, as the default 1.5 version is no longer recognized.
- [ ] Bugzilla - Since the landfill was not working, I used Docker image for setting up.
- [ ] Dockerized the ninacrm and lab6 applications.
- [ ] In the original folder, the .project and Eclipse settings files are checked in. When you use the latest Eclipse with JDK, there were multiple errors thrown. I could override this by removing all IDE specific files from the main branch.

**Comment by jadelkhoury** [comment]
Hi

So are you set up and runnign otherwise? Any blocking issues? 


> * [ ]  POM - The java version needs to be provided correctly, as the default 1.5 version is no longer recognized.

Are you sure? From what I see under this link, java is set to 1.8.
https://github.com/eclipse/lyo.docs/blob/5f4737d96835924714d4e7107342ed30c2552235/lyo-rest-workshop/Lab6/pom.xml#L11

> * [ ]  Bugzilla - Since the landfill was not working, I used Docker image for setting up.

Would be great if you can share which image you used and/or configured.

> * [ ]  Dockerized the ninacrm and lab6 applications.

Would be great if you can share which image you used and/or configured.

> * [ ]  In the original folder, the .project and Eclipse settings files are checked in. When you use the latest Eclipse with JDK, there were multiple errors thrown. I could override this by removing all IDE specific files from the main branch.

These are actually maven projects, and it is unfortunate that the eclipse files were added to the git repository. We should remove these files. 
Instead, the instructions (for those using Eclipse) is to import the project (as a maven project). This will create the needed Eclipse project files accordingly. After that, one can press alt+F5 to update the project from the maven pom file.
But aren't you using IntelliJ? In that case, i think you should ingore these files.

**Comment by shameerkc** [comment]
Hi

1. POM Issue - present only for the ninacrm POM File [https://github.com/eclipse/lyo.docs/blob/5f4737d96835924714d4e7107342ed30c2552235/lyo-rest-workshop/ninacrm/pom.xml](https://github.com/eclipse/lyo.docs/blob/5f4737d96835924714d4e7107342ed30c2552235/lyo-rest-workshop/ninacrm/pom.xml)

2. I did not push the image yet to Docker Hub. Please have a look at the repository [https://github.com/shameerkc/docker-bugzilla-sqlite](https://github.com/shameerkc/docker-bugzilla-sqlite) for details.

3. The DockerFile are included in [https://github.com/shameerkc/OSLC-Lyo-Workshop-Projects](https://github.com/shameerkc/OSLC-Lyo-Workshop-Projects)

4. You are right. Ignoring the files solves the problem. It was just a suggestion only to avoid committing the IDE setting files to main branch.

**Comment by jadelkhoury** [comment]
Nice! So it seems that you have things in place already. So you can actually run the complete lab already?
I hope I can soon update these instructions to reflect the problems you have raised. (plus use docker for Bugzilla)

**Comment by shameerkc** [comment]
Yes Jad, I verified the integrations using Bugzilla as well as the applications running as containers.

**Comment by jadelkhoury** [comment]
@shameerkc  I have made 2 pull-requests that remedy the problems you have identified.
Thanks for pointing them out.

https://github.com/eclipse/lyo.docs/pull/7

https://github.com/OSLC/developing-oslc-applications/pull/13
