### ISSUE TITLE
Hands-on CM tutorial link broken

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/developing-oslc-applications#14]
https://oslc.github.io/developing-oslc-applications/tutorials.html points to https://github.com/eclipse/lyo.docs/blob/master/lyo-rest-workshop/Lab1/Lyo_OSLC_Workshop.pdf

**Comment by jadelkhoury** [comment]
Thanks Andrii. Problem solved.

**Comment by jadelkhoury** [comment]
https://github.com/OSLC/developing-oslc-applications/commit/152cd7da24c2df261e182ac1859d13691767e902 for teh record.
