### ISSUE TITLE
Add a link to go up

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/developing-oslc-applications#19]
Eg from https://oslc.github.io/developing-oslc-applications/eclipse_lyo/eclipse-lyo.html

**Comment by berezovskyi** [comment]
Works everywhere except https://oslc.github.io/developing-oslc-applications/integrating_products_with_oslc/, which is messed up

**Comment by jadelkhoury** [comment]
Real nice! Found the site confusing to navigate otherwise.
Just one bug I found which is worth fixing, while you have this open? 
The link "one level up" from https://oslc.github.io/developing-oslc-applications/integrating_products_with_oslc/running_the_examples.html is broken

**Comment by berezovskyi** [comment]
Oh yes, forgot to fix that one. The links have to be relative.

**Comment by berezovskyi** [comment]
Fixed
