### ISSUE TITLE
Page rendering is buggy

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/developing-oslc-applications#3]
https://oslc.github.io/developing-oslc-applications/

SSL warning probably is about non-HTTPS resources load attempts.

**Comment by jamsden** [comment]
http://oslc.github.io/developing-oslc-applications/ should be used, the site isn't configured for SSL that I know of.

**Comment by berezovskyi** [comment]
right, so the links with https need to be corrected then

**Comment by berezovskyi** [comment]
or the `http://` references in HTML shall be replaced with `//`
