### ISSUE TITLE
Broken tutorial links at the front page.

### ISSUE THREAD

**Issue by jadelkhoury** [OSLC/developing-oslc-applications#5]
The potentialy very useful links on the front page (Explore our tutorial http://oslc.github.io/developing-oslc-applications/) are broken. They point to the archive of open-services.

Suggestion: let's migrate these tutorial pages to http://oslc.github.io/developing-oslc-applications/!

**Comment by jadelkhoury** [comment]
@berezovskyi @jamsden I mention you here to take your opinion on this!

**Comment by jamsden** [comment]
It would only take a minute to fix the broken links, longer to move the content, even longer to see what's still relevant or has been replaced.

**Comment by jadelkhoury** [comment]
Bugzilla is unfortunatly still the only comprehensive tutorial we have. I think it is worth putting some effort on it.
I'm willing to at least the effort to "move the content".
If I do that step, I might also get an impression to see what it takes to improve it.
But first, do we agree that the content belongs to this website?

**Comment by berezovskyi** [comment]
I agree we should move the content. I will ask Gabriel for the HTML sources of the archive.

**Comment by berezovskyi** [comment]
Or easier... @gabrielfdac, could you please give me access to the archive site source or ZIP up the https://open-services.net/resources/tutorials folder for me, please?

**Comment by jadelkhoury** [comment]
Lost the time I had to improve the docs, so now going for Jim's first quick suggestion.
https://github.com/OSLC/developing-oslc-applications/pull/6

**Comment by jadelkhoury** [comment]
@jamsden @berezovskyi 
The change is NOT reflected in http://oslc.github.io/developing-oslc-applications/.

Did I miss a step in the release of the pages to the site?

I have merged this change to the gh-pages branch: The change also include changes to both the md and the html pages. Specifically, see the "get-started.html".
https://github.com/OSLC/developing-oslc-applications/blob/gh-pages/get-started.html

**Comment by jamsden** [comment]
Here's my notes on how to update OSLC Developer Guide:

Here’s a typical development and publish process
1. fork the gh-pages branch
2. npm install -g harp
3. harp server _harp
4. visit http://localhost:9000 to see the site
5. Make edits to the site…, source markdown files are in the _harp folder. Files that start with _ are not served by the server
6. The navigation bar is -harp/_data.json
7. harp compile _harp ./
8. git add -A
9. git commit
10. git push
Sometime after the git push, as much as 10 minutes, the update content will be visible at http://oslc.github.io/developing-oslc-applications/

Did you do the harp compile? That would be required to generate the HTML files from the markup changes you made.

**Comment by jadelkhoury** [comment]
Yes, i did the harp compile which is what produced the updated html pages. 
In the end, what counts is the "get-started.html" page. 
https://github.com/OSLC/developing-oslc-applications/blob/gh-pages/get-started.html

To be exact, after “10. git push”, I did the “11. Merge the branch into gh-pages”

**Comment by berezovskyi** [comment]
Hmm https://stackoverflow.com/a/27809833

Could you please make a new commit and just do 'touch index.html'?

**Comment by jadelkhoury** [comment]
I now even did a silly change on the get-started.html page.  
https://github.com/OSLC/developing-oslc-applications/commit/4483e879fc097ce9049e385c126db97b5e9d39aa

Still no good.

**Comment by jadelkhoury** [comment]
And now even a more visible change for easier debugging. I replaced “you’re” with “you are” :-)

https://github.com/OSLC/developing-oslc-applications/commit/607061f272f3d4c4c4ce9cb66c1cd7068a7a5575

**Comment by berezovskyi** [comment]
No! https://github.com/OSLC/developing-oslc-applications/blob/gh-pages/index.html You got to update this page

**Comment by jadelkhoury** [comment]
Mistery solved.
I was updating the "get-started.md" file, which is not used at all. The "get started" menu maps to the index page. Ok, I will update (and delete get-started.md").

Thanks @berezovskyi

**Comment by jadelkhoury** [comment]
Now solved. Thanks for hte help.
