### ISSUE TITLE
Integrate the Bugzilla Workshop into this "OSLC Developer Guide" site

### ISSUE THREAD

**Issue by jadelkhoury** [OSLC/developing-oslc-applications#7]
1.
The md source for the Bugzilla worshop (https://archive.open-services.net/resources/tutorials/integrating-products-with-oslc/) is under https://github.com/OSLC/integrating-products-with-oslc-tutorial.

Is it better to migrate this content into this repo? 
This also implies we no longer need to refer to https://archive.open-services.net/resources/tutorials/integrating-products-with-oslc/.

2. At the very least, we update the content to refer to the proper location of the source code.
https://github.com/eclipse/lyo.docs/tree/master/lyo-rest-workshop

**Comment by jadelkhoury** [comment]
@jamsden @berezovskyi  
Finally found the missing content. Both the instructions and the code.
Makes sense to move it?

**Comment by berezovskyi** [comment]
Great. Makes total sense

**Comment by jadelkhoury** [comment]
@gabrielfdac We discussed Lyo documentation under https://github.com/eclipse/lyo/issues/8, and I am under the impression you are/were involved in the migration of some of the content under open-services.net?

What do you think of my suggestion above? I am suggesting to move the Bugzilla tutorial to be under https://oslc.github.io/developing-oslc-applications/, instead of the "archive.open-services.net" location.

if agree, can you confirm the source of the content for your Bugzilla tutorial under open-services? the content under https://github.com/OSLC/integrating-products-with-oslc-tutorial does not seem to be an exact match, and I would like to figure out which the final source.

**Comment by berezovskyi** [comment]
@jadelkhoury links for https://open-services.net/resources/developing-oslc-applications/ sources:

https://github.com/OSLC/oslc-site-hugo/blob/3b32a7efde35ed5c7fc1e666b7bc8c4b65572c13/content/resources/developing-oslc-applications.md

**Comment by berezovskyi** [comment]
The tutorial in question has not been migrated: https://archive.open-services.net/resources/tutorials/integrating-products-with-oslc/

**Comment by jadelkhoury** [comment]
We should really remove the content https://open-services.net/resources/developing-oslc-applications/ from the open-services.net site. It is a copy of https://oslc.github.io/developing-oslc-applications/ and is already out of date.
I refuse to believe that LinkData people copy content around. LINK! 
Who do I talk to about this?

> The tutorial in question has not been migrated: https://archive.open-services.net/resources/tutorials/integrating-products-with-oslc/

You mean it does not exist as md-files?

**Comment by berezovskyi** [comment]
I can remove it and no, there are no md files for that tutorial.

--
/Andrew
(from phone)



On Tue, May 21, 2019 at 8:27 AM +0200, "Jad El-khoury" <notifications@github.com<mailto:notifications@github.com>> wrote:


We should really remove the content https://open-services.net/resources/developing-oslc-applications/ from the open-services.net site. It is a copy of https://oslc.github.io/developing-oslc-applications/ and is already out of date.
I refuse to believe that LinkData people copy content around. LINK!
Who do I talk to about this?

The tutorial in question has not been migrated: https://archive.open-services.net/resources/tutorials/integrating-products-with-oslc/

You mean it does not exist as md-files?

**Comment by jadelkhoury** [comment]
> I can remove it and no, there are no md files for that tutorial.

and please redirect the link at https://open-services.net/resources/ to https://oslc.github.io/developing-oslc-applications/

**Comment by berezovskyi** [comment]
> and please redirect the link at https://open-services.net/resources/

Nope, can't do that. Did you check that link? There are many resources linked from it.

**Comment by berezovskyi** [comment]
Done. Please review https://github.com/OSLC/oslc-site-hugo/pull/243

**Comment by jadelkhoury** [comment]
Looks good.

I meant the link within https://open-services.net/resources/. Please see pic!
![image](https://user-images.githubusercontent.com/7108694/58082169-bb691080-7bb6-11e9-8775-728c0421ba02.png)

**Comment by berezovskyi** [comment]
yes, that one now refers to OSLC Dev Guide
